version: '2.3'
services:

  jupyterlab:
    build:
      context: .
      dockerfile:  ./Dockerfile
    container_name: vscode_server
    restart: always
    environment:
      - PASSWORD=$VSCODE_SERVER
      - DOCKER_USER=$USER
    # ports:
    #   - "8080:8080"
    volumes:
      - /home/volokzhanin/server:/root/code
      - /home/volokzhanin/.ssh:/root/.ssh
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-modeset
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    runtime: nvidia
    networks:
        - default

networks:
  default:
    external: true
    name: volokzhanin


